version: '2.18'
services:
  python-app:
    image: jonathinsm/pythondemoapp:latest
    container_name: my-python-app
    restart: always
    ports:
      - 8000:8000
  database:
    image: mongo:6-jammy
    ports:
      - 27017:27017
